version: '3.8'

services:
  smart-court-ai:
    build: .
    container_name: smart_court_ai
    restart: always
    ports:
      - '8501:8501'
    volumes:
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml
      - ./credentials.json:/app/credentials.json
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
